### ISSUE TITLE
Move Kundenseiten page to Kunden header

### ISSUE THREAD

**Issue by DavidFritsch** [DefactoSoftware/website#1039]
Move the page Kundeseiten from "Über uns" to "Kunden

**Comment by DavidFritsch** [comment]
I mean to move "Kundenstimmen" from "Über Uns" to "Kunden"

**Comment by RonaldDijkstra** [comment]
Yeh, probably later on when there are cases.

**Comment by RonaldDijkstra** [comment]
Done
