### ISSUE TITLE
Cookie notice

### ISSUE THREAD

**Issue by Kuret** [DefactoSoftware/website#1052]
We are placing cookies(including third party) on the website so we are legally required to give a cookie notice. ('Ik ga akkoord...')

Also regarding session recording, it appears just a cookie notice isn't clear enough and could be interpreted by law as 'computerhuisvredebreuk'
More info: https://tweakers.net/reviews/5991/sessionrecording-hoeveel-websites-nemen-bezoeksessies-op-en-mag-dat-zomaar.html

> "Wij plaatsen cookies ja/nee" onvoldoende is voor toestemming voor sessionrecording. "Een korte omschrijving inclusief doelomschrijving en een link naar de volledige voorwaarden zou al genoeg kunnen zijn, mits daarbij duidelijk gevraagd wordt om toestemming. Maar dan mag het dus niet zo zijn dat er alvast cookies worden geplaatst voordat men op Ja heeft kunnen klikken."

> Hoogleraar informatierecht Nico van Eijk merkt in deze context nog op dat als een website niet expliciet en op een duidelijke plek om toestemming vraagt, en dus de cookiebepaling uit de Telecommunicatiewet niet naleeft, dit al snel in het vaarwater van het strafrecht komt. "De activiteiten bij sessionrecording kunnen dan gezien worden als een vorm van computerhuisvredebreuk en gegevensdiefstal wanneer geen toestemming is verkregen. Het is dan in wezen een vorm van hacking."

**Comment by RonaldDijkstra** [comment]
We use [hotjar](https://www.hotjar.com) so this is very good point.

**Comment by RonaldDijkstra** [comment]
https://cookieconsent.insites.com/documentation/javascript-api/

**Comment by RonaldDijkstra** [comment]
- [ ] Add a page about our privacy policy
- [ ] Add cookie consent (block all before consent?)

**Comment by RonaldDijkstra** [comment]
We do not use hotjar anymore. But this is still urgent.
