### ISSUE TITLE
Update RIVM logo (better quality)

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/website#1154]
The one on the website is a bit low res.

![rivm](https://user-images.githubusercontent.com/935529/38671027-9e3df660-3e4a-11e8-8e6f-56b01035c9b7.png)

**Comment by MarinkeDefacto** [comment]
Do you mean in the client section? https://www.defacto.nl/klanten/

**Comment by sn3p** [comment]
> Do you mean in the client section? https://www.defacto.nl/klanten/

Yes, it looks a bit blurry. Maybe a side-effect from scaling, but the other logos look slightly sharper.

**Comment by MarinkeDefacto** [comment]
I'l use this one en scall it. We will see if it gets better.
