### ISSUE TITLE
video op home pagina

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#119]
graag het video op de website. hier de youtube link, heb ook de file als die nodig is.

https://youtu.be/T3vnuBY4h7c

**Comment by RonaldDijkstra** [comment]
Hi Isa, what do you exactly want with the video?

**Comment by RonaldDijkstra** [comment]
![defacto developing people - hero video](https://cloud.githubusercontent.com/assets/16101007/11893196/e33608c4-a56e-11e5-95bf-7a4fc3f02877.png)

Something like this?

**Comment by isabelamy** [comment]
no! i don't think it should be so big and center. 
not sure where it should be, but definitely under the product description.
so in between here 
<img width="1280" alt="screen shot 2015-12-18 at 10 15 42" src="https://cloud.githubusercontent.com/assets/5277505/11893359/58f0738c-a570-11e5-8d4c-ceed6513407a.png">

**Comment by dkhgh** [comment]
Just ask @sn3p to weigh in on this

**Comment by sn3p** [comment]
@isabelamy maybe we should accompany the video with some information on what it's about or what to expect. What do we actually want to tell the viewer?

**Comment by isabelamy** [comment]
or maybe a section 'what our clients say' and under it 'what we say'.
or 'defacto in the press' / 'defacto media' / 'defacto news' or something like that?
we could put in an agenda with the next events or a short news announcement or is that too oldfashion?
@sn3p
