### ISSUE TITLE
Update privacy policy and more 🇩🇪

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#1236]
We need: 

- [x] Updated Privacy Policy (like on the :netherlands: website https://www.defacto.nl/privacy-policy/)
- [x] Impressum (see websites of some 🇩🇪 competitors, zum beispiel easysoft)
- [x] AGB (Allgemeine Geschäftsbedingungen)?! Not sure about this one! 

I can make all pages we need but as always need input for that.

**Comment by CathrinH** [comment]
@SusanDefacto Weet jij meer over de 'Impressumspflicht' en wat dat precies inhoudt?

**Comment by SusanDefacto** [comment]
@CathrinH Impressum is not that special. Privacy Policy and AGB are kind of tricky. I do have some basic information about the topic 'Privacy Policy'. Normally you send the AGB with every offer? If so we'll have some basic information about the AGB as well.

**Comment by RonaldDijkstra** [comment]
How about AGB?
