### ISSUE TITLE
Add events to events calendar 

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#1354]
We do not have any planned things on the website at this point. 

https://www.defactolearning.de/veranstaltungskalender/

**Comment by lennartdefacto** [comment]
What we could add here are the event Arnoud & Susan are going to (18 okt), and the DE userday (just as an FYI, not with a form ofcourse). Next item would be the CAPP LMS launch in January? Also Learntec and OEB(?) could be added as 'you can find us here' events.

**Comment by RonaldDijkstra** [comment]
18 okt Susan & Arnoud
15 nov User Day
Learntec
OEB

**Comment by RonaldDijkstra** [comment]
Can we add some more here? https://www.defactolearning.de/veranstaltungskalender/

**Comment by RonaldDijkstra** [comment]
All is well
