### ISSUE TITLE
Styling and layout improvements

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/website#140]
- [x] Capitalize header navigation (instead of uppercase) (https://github.com/DefactoSoftware/website/pull/159)
- [x] Footer navigation headers should be links (Producten, Diensten, etc.) (https://github.com/DefactoSoftware/website/pull/159)
- [ ] Header navigation dropdowns (Producten, Diensten, etc.), I think this looks really cool:
## 

<img width="936" alt="screen shot 2016-01-07 at 11 17 01" src="https://cloud.githubusercontent.com/assets/935529/12168075/59e45bbc-b530-11e5-900f-50440f27741b.png">

**Comment by RonaldDijkstra** [comment]
I'll open a new issue for the third item!
