### ISSUE TITLE
LMS Domain Configurator

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#1413]
- Ask questions 
- Show answers in a graph (probably send the graph and information afterwards with e-mail) 
- So: contact options

**Comment by RonaldDijkstra** [comment]
https://www.highcharts.com/ 
https://www.chartjs.org/

**Comment by RonaldDijkstra** [comment]
Use fancy slider shizzle like https://codepen.io/chrisgannon/pen/rvBMmM 

🤣

**Comment by RonaldDijkstra** [comment]
Maybe in another project instead of the website

**Comment by RonaldDijkstra** [comment]
A quote about this: 

> a test that is based on the domain concept and ultimately provides a result / profile in graphical form

**Comment by RonaldDijkstra** [comment]
Questionnaire https://github.com/DefactoSoftware/Questionnaire

**Comment by sn3p** [comment]
To proceed we need:

1. dedicated questions page
2. with a form (formkeep)
3. dedicated results pages (redirected to by the form)

**Comment by RonaldDijkstra** [comment]
Crazy 👍
