### ISSUE TITLE
German 404 redirect

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/website#143]
Not properly working yet.
Possibly related to [this piece of code](https://github.com/DefactoSoftware/website/blob/master/source/localizable/404.html.erb#L5-L19).

**Comment by RonaldDijkstra** [comment]
soft 404 because of the redirect. Status 200 is returned

**Comment by RonaldDijkstra** [comment]
On the new domain the site returns a 404 status code. Closed
