### ISSUE TITLE
Add OEB event 

### ISSUE THREAD

**Issue by CathrinH** [DefactoSoftware/website#1468]
OEB (ehem. ONLINE EDUCA BERLIN)
Shaping the future of learning 

When: 
5. - 7. Dezember 2018 

Where: 
Hotel InterContinental, Berlin
https://oeb.global/conference#location-venue

Text:
Es ist wieder Zeit für die globale, branchenübergreifende Konferenz und Ausstellung über technologiegestütztes Lernen und Training in Berlin. Die OEB verschiebt seit 24 Jahren Grenzen, stellt vorgefasste Meinungen in Frage und fördert und formt neue Ideen über die Zukunft von Digitalem Lernen. In der Ausstellung werden Innovationen präsentiert, Sprecher zeigen neue Lernformen auf und regen zur Diskussion an. Bei der OEB können Sie das Unerwartete erwarten. 
Wir freuen uns dieses Jahr bei der OEB teilzunehmen. Kommen Sie uns an unserem Stand "L10" besuchen.

Mehr Informationen [LINK: https://oeb.global/]

@isabelamy check jij de tekst?

**Comment by RonaldDijkstra** [comment]
Please use a more descriptive title, like: 

Add OEB event
