### ISSUE TITLE
Add Learntec 2019 to events

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#1482]
Titel: Launch von CAPP LMS bei der Learntec 2019
Subtitel: Ein Blick in die Zukunft von Learning & Talent Management
Time/location: 29.01. - 31.01.2019 | Messe Karlsruhe 
Text: Wenn Sie auf der Suche sind nach digitalen Lerntrends sind sie bei der Learntec genau richtig. Auf Deutschlands wichtigster digitalen Bildungsmesse stellen wir dieses Jahr unsere neue Version **CAPP LMS** offiziell vor. Besuchen Sie uns am Stand K32 in Halle 2 und erfahren Sie mehr!
Mehr zur Messe (https://www.learntec.de/de/learntec/die-fachmesse/)

**Comment by RonaldDijkstra** [comment]
Please use a more descriptive title, for example: 

Add Learntec 2019 to events

It's for history purpose ;-)

**Comment by isabelamy** [comment]
Sorry :)

**Comment by RonaldDijkstra** [comment]
Nvm!
