### ISSUE TITLE
How to deal with passed events?

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#1485]
The event @aknoeff attended was yesterday, so....how to deal with the past events?

## Show an archive?

> **Current events**
> Events list
> 
> **Passed events**
> Events list 

## Remove them?

**Comment by isabelamy** [comment]
I think I'm for removing.

**Comment by isabelamy** [comment]
If an event is interesting we'll write a blog about it.

**Comment by RonaldDijkstra** [comment]
All good.
