### ISSUE TITLE
Translate Service & Support page

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#1497]
We made a Dutch page about our Service & Support team. Should be translated and published on Defactolearning.de as well.

**Comment by RonaldDijkstra** [comment]
It's just translating this text: https://www.defacto.nl/support/

**Comment by RonaldDijkstra** [comment]
Status?

**Comment by lennartdefacto** [comment]
Re-upped the request for text-check by colleagues
