### ISSUE TITLE
Layout of productoverview page

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#157]
This is about: http://www.defacto.nl/producten/

There's a suggestion to make the productoverview layout more like this beurswand:

![bollen-beurswand](https://cloud.githubusercontent.com/assets/16101007/12546584/1a5990ce-c34b-11e5-8668-7c8b04866b27.png)

What's your view on this, @sn3p?

**Comment by fatboypunk** [comment]
:-1: I don't like it tbh

**Comment by RonaldDijkstra** [comment]
The layout as is is just fine by me.
