### ISSUE TITLE
Add supportteam vacancy

### ISSUE THREAD

**Issue by LizetteJS** [DefactoSoftware/website#1665]
Graag onderstaande tekst:

Voor ons kenniscentrum, dat onder andere verantwoordelijk is voor het support en implementatie van het Learning Management Systeem CAPP LMS, zijn we op zoek naar versterking waarbij de focus ligt op consultancy. Het betreft een full-time functie voor een langere periode.

Als consultant is het jouw taak contactpersonen van onze klanten te helpen bij de implementatie van en vragen over ons Learning Management Systeem. Dit doe je voornamelijk op afstand (intern), indien het nodig is bezoek je onze klanten ook op locatie (extern). Je vindt het vanzelfsprekend dat jij je in onze software verdiept en deze eigen maakt. Je ontwikkelt je graag tot kennisdrager binnen onze organisatie. Je bent proactief, vindingrijk en een teamplayer die niet schrikt van eigen verantwoordelijkheid dragen, verder herken jij je in de volgende punten:

Hbo of wo opleiding / niveau
Uitstekende communicatieve en sociale vaardigheden
Affiniteit met software
Flexibele instelling
Herken jij je in bovenstaande omschrijving? Dan kun je gelijk bij ons aan de slag. Eerst een dag meelopen? Geen probleem! Heb je interesse? Solliciteer via onderstaande button.

Wat bieden we
Een goede werksfeer in een tof team
Een competitief salaris
Ruime opleidingsmogelijkheden en -budget
Ruimte voor eigen initiatief
Een gunstige Bring Your Own Device- en lunch-regeling
Een omgeving die leren en kennisdeling stimuleert
Defacto Software
Defacto beweegt zich al jaren als toonaangevend ontwikkelaar van innovatieve software in het werkveld van opleiden en ontwikkelen. Defacto is uitgegroeid tot een solide, internationaal opererend bedrijf. De kernactiviteiten bestaan uit het digitaliseren en automatiseren van opleidingsafdelingen, bedrijfsacademies en opleidingsinstituten.

Defacto kent een platte organisatie en hoge mate van transparantie. De verantwoordelijkheid ligt op de werkvloer bij de mensen zelf en wordt door de mensen zelf ook bewaakt.

We geloven dat het belangrijk is om in een leuke omgeving te kunnen werken. Onze werktijden zijn flexibel, het gaat om de kwaliteit die je levert.

**Comment by LizetteJS** [comment]
Het bovenste stuk tekst mist op de website https://www.defacto.nl/jobs/support-consultant/

**Comment by LizetteJS** [comment]
Voor ons kenniscentrum, dat onder andere verantwoordelijk is voor het support en implementatie van het Learning Management Systeem CAPP LMS, zijn we op zoek naar versterking waarbij de focus ligt op consultancy. Het betreft een full-time functie voor een langere periode.

**Comment by RonaldDijkstra** [comment]
Mkay
