### ISSUE TITLE
Add Sana Logo 

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#1681]
Sana logo has to be implemented on the German website.
- Homepage
- Kunden
- CAPP Agile Learning

![logo-sana-ag 2x](https://user-images.githubusercontent.com/5277505/52277071-16526100-2954-11e9-86f1-e6240d2c24b1.png)

**Comment by dkhgh** [comment]
Need better quality probably

**Comment by RonaldDijkstra** [comment]
https://commons.wikimedia.org/wiki/File:Sana_Kliniken_logo.svg 

We could use this SVG

**Comment by isabelamy** [comment]
Can this please be implemented? It's been 21 days....

**Comment by RonaldDijkstra** [comment]
On it
