### ISSUE TITLE
Add a part about solutions

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#1683]
I think we need an additional menu item called solutions(EN) / Lösungen(DE) / Oplossingen(NL)

For the German website I would want the following pages under that menu:
- Gesundheitswesen
- Verkehr und Logistik
- Performance Support
- E-Learning

**Comment by RonaldDijkstra** [comment]
https://defacto.cappagile.com/spaces/defacto-websites-2018/chapters/solutions-oplossingen?group=3

**Comment by RonaldDijkstra** [comment]
We have an issue about this #1377 with a slightly different approach. Marketing is leading here, so let me know what route we want to take with these.

**Comment by RonaldDijkstra** [comment]
When we do this we need: 

- at least 1 subpage to start with (I don't care which one)
- index page

**Comment by isabelamy** [comment]
can you merge the issues? i don't care which one we use.
here is the first subpage: https://defactosoftwarebv.sharepoint.com/:w:/r/_layouts/15/Doc.aspx?sourcedoc=%7B372BB058-8D17-4789-A215-C71258F44E0F%7D&file=gesundheitswesen%20seite.docx&action=default&mobileredirect=true

There is no design or pics yet. So suggestions are welcome :)

**Comment by isabelamy** [comment]
I don't think we will use personas anytime soon btw. But maybe we can do something like 'trends' or 'topics' where we'll could have subpages on performance support, online learning/e-learning, curation or something like that

**Comment by RonaldDijkstra** [comment]
> can you merge the issues? i don't care which one we use.

This one, other one is closed. Thank you.

**Comment by isabelamy** [comment]
right now [themes] is kind of hidden away. let's first start with getting a main menu item [solutions]. i'll work on getting another subpage for it this week/next week.

**Comment by RonaldDijkstra** [comment]
So themes is solutions?

**Comment by isabelamy** [comment]
I think themes should stay themes and solutions should be a new main menu item. so before or after products.

Themes are more temporary, like 70-20-10 or 5 moments of need.

Solutions are permanent. Like industry solutions (health care, pharma etc.) and process solutions (performance support, HRD etc.)

**Comment by lennartdefacto** [comment]
> I think themes should stay themes and solutions should be a new main menu item. so before or after products.

I'd put it in between products and services.

> Solutions are permanent. Like industry solutions (health care, pharma etc.) and process solutions (performance support, HRD etc.)

So would you like a "solutions" menu item with a drop-down structure like this?
- Solutions for different branches (this linking to a page where people can click on a branche)
- Solutions for different processes (the linking to a page where a person can click on different processes)

If we would do all the branches and all the processes directly under the main dropdown it would be quite lengthy (especially if we'd later add new ones)

**Comment by isabelamy** [comment]
what's the status?

**Comment by lennartdefacto** [comment]
We stil need to make choices regarding the general concept of a solutions page(or pages), like I asked in my previous comment. I'm still in favor of it being a a seperate menu option, with the drop down options 'solutions [categorized] by branche' en 'solutions [categorized] by proces'.

If this is agreed upon, than we can start mapping it out in a more concrete fashion; which processes/branches. The step after this is creating content (Michel and myself) and putting it up for review.

**Comment by RonaldDijkstra** [comment]
```
- Products 
  - LMS
  - Passport
  - Monitor
  - API 
  - Quizzes
  - Agile Learning

- Solutions
  - Industry
    - Healthcare
    - Transport and logistics
    - ?
  - Process
    - Performance Support (this is just a theme like 70:20:10, right?)
    - E-Learning (whats on this) 
    - ?

- Services
  - Implementations
  - Hosting & Security
  - Integrations 
  - ~E-learning~ be gone because solutions/e-learning

- Clients
  - Cases
  - Testimonials 

- Defacto
  - About us
  - Servicedesk (probably move it to services)
  - Blog
  - Themes (let's remove this in favor of solutions)
  - Open Source 
  - Event calendar
  - Contact us

- Request a Demo
```

**Comment by isabelamy** [comment]
Well so far I only have one page for the German website for under solutions, so how about we start with that.

In general I am for categorizing it in Branche and process.

**Comment by RonaldDijkstra** [comment]
Sure thing

**Comment by RonaldDijkstra** [comment]
@isabelamy

- As we cannot use ö in a page path: should the page path of Solutions in German be "losungen" or "loesungen"? 
- Please deliver metadata too (title + description)

**Comment by RonaldDijkstra** [comment]
> can you merge the issues? i don't care which one we use.
> here is the first subpage: https://defactosoftwarebv.sharepoint.com/:w:/r/_layouts/15/Doc.aspx?sourcedoc=%7B372BB058-8D17-4789-A215-C71258F44E0F%7D&file=gesundheitswesen%20seite.docx&action=default&mobileredirect=true
> 
> There is no design or pics yet. So suggestions are welcome :)

What would be the page path of this?

**Comment by isabelamy** [comment]
/loesungen/gesundheitswesen

**Comment by RonaldDijkstra** [comment]
alright

**Comment by RonaldDijkstra** [comment]
loesungen/page-path is better

**Comment by isabelamy** [comment]
content for page is ready. i made some suggestions about the structure of the page, if there are any questions please let me know.
https://defactosoftwarebv.sharepoint.com/:w:/r/_layouts/15/Doc.aspx?sourcedoc=%7B372BB058-8D17-4789-A215-C71258F44E0F%7D&file=gesundheitswesen%20seite.docx&action=default&mobileredirect=true

**Comment by RonaldDijkstra** [comment]
Allgemein |  Lernplattform  |  Personalentwicklung  |  Referenzen 

This is some sort of page navigation?

**Comment by isabelamy** [comment]
yes. like in the product pages.
<img width="765" alt="screenshot 2019-03-04 at 12 30 27" src="https://user-images.githubusercontent.com/5277505/53730810-4ddffa80-3e79-11e9-8656-4352a2f1c3c9.png">
