### ISSUE TITLE
Move e-learning page to themes

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#1685]
This page https://www.defactolearning.de/e-learning/ has to be under 'Defacto --> Themen' with the Titel 'E-Learning im Gesundheitswesen'.

**Comment by RonaldDijkstra** [comment]
So themen/e-learning/ ?

**Comment by isabelamy** [comment]
yes

**Comment by RonaldDijkstra** [comment]
Cool

**Comment by isabelamy** [comment]
can this please be moved? i want to link it in the new solutions/health care page.

**Comment by RonaldDijkstra** [comment]
What with this page in other languages then?

**Comment by isabelamy** [comment]
do they also have to move then? well if it's not possible without moving it in the other languages than i can write a quick text about e-learning as a placeholder. but then i would want a new page with the current content in the submenu 'themes'.

**Comment by isabelamy** [comment]
do we still have the old content of that page somewhere?

**Comment by RonaldDijkstra** [comment]
No they can stay for sure, but if the website is very different per language, it does have implications for managing and maintaining the content. The solutions healthcare page doesn't have to link to this e-learning page straight away right? Gonna put in the link later on.

Which page?

**Comment by isabelamy** [comment]
yeah i get that. and we definitely need a page about e-learning. although i also think that we can eventually put it under solutions instead of services?

We used to have a different content on the e-learning page that was more general and not health care specific. But I guess we don't have that anymore?

**Comment by RonaldDijkstra** [comment]
We always have everything because git version control.

**Comment by RonaldDijkstra** [comment]
I think you want this @isabelamy 

https://github.com/DefactoSoftware/website/blob/f838f4b4fec0951374716d5ff40aea7f6433b270/source/localizable/elearning/_elearning.de.md.erb

**Comment by RonaldDijkstra** [comment]
Or this: https://github.com/DefactoSoftware/website/blob/cd53d795e59ccc556d5cdee4f6b3091a04fa0762/source/localizable/elearning/_elearning.de.md.erb

Commit history with touches of the e-learning file: https://github.com/DefactoSoftware/website/commits/master/source/localizable/elearning/_elearning.de.md.erb

**Comment by isabelamy** [comment]
@lennartdefacto kun je op basis hiervan een pagina voor https://www.defactolearning.de/e-learning/ maken, zodat we de huidige pagina kunnen verplaatsen? 

[e-learning.pptx](https://github.com/DefactoSoftware/website/files/2946198/e-learning.pptx)
