### ISSUE TITLE
Add testimonial SANA

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#1720]
This one should go under 'Kundenstimmen':

„Als Maximalversorger brauchen wir ein flexibles E-Learning-System, um den unterschiedlichen Bildungsbedarf unserer 56 Häuser, Einrichtungen und Dienstleistungsgesellschaften der Sana-Kliniken in vollem Umfang abzudecken.

Mit einer modernen digitalen Lernplattform sorgen wir dafür, dass unsere Mitarbeiter immer auf dem neuesten Wissensstand sind. Damit legen wir den Grundstein für mehr Qualität und Sicherheit in der Versorgung unserer Patienten – zum Beispiel bei der korrekten Gabe von Medikamenten oder der Einhaltung von Hygienestandards.

Zugleich möchten wir durch ein individualisiertes digitales Qualifizierungsangebot die Zufriedenheit unserer Mitarbeiter steigern.“ - Jutta Geringhoff, Bereichsleiterin Personalentwicklung und Personalmarketing (Sana AG)

![3_geringhoff](https://user-images.githubusercontent.com/5277505/54030332-91a16f80-41ab-11e9-80ca-1d95663c66dd.jpg)

The first part should also be used as a short quote under 'Gesundheitswesen'. Either additionally or instead of the one from Anne Monier.

**Comment by RonaldDijkstra** [comment]
Will see how it works out to use a summary.

**Comment by RonaldDijkstra** [comment]
Don't we want this translated in 🇳🇱 ?
