### ISSUE TITLE
Add testimonial FEK

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#1721]
I saw that we have a quote in the FEK case. That quote should also be under 'Kundenstimmen' and on the homepage instead of Anne Monier's quote.
<img width="331" alt="screenshot 2019-03-08 at 15 32 02" src="https://user-images.githubusercontent.com/5277505/54035041-b223f680-41b8-11e9-850a-d4f4b3e6b86d.png">

**Comment by RonaldDijkstra** [comment]
@lennartdefacto this is yours

**Comment by RonaldDijkstra** [comment]
When? 🍔

**Comment by lennartdefacto** [comment]
Working on it at this very moment.
