### ISSUE TITLE
Add user case

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#1722]
@lennartdefacto can this be formed into a user case for the website? Please in the same format as the other user cases. If you need more info let me know.

It shouldn't go online before April though!!

[Anwenderbericht_Das Krankenhaus_frei Geringhoff.docx](https://github.com/DefactoSoftware/website/files/2946215/Anwenderbericht_Das.Krankenhaus_frei.Geringhoff.docx)

**Comment by RonaldDijkstra** [comment]
Hows this goin?
