### ISSUE TITLE
Add SANA blog

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#1733]
https://defactosoftwarebv.sharepoint.com/:w:/r/_layouts/15/Doc.aspx?sourcedoc=%7BF3E12ADA-333F-4A6E-9D28-7FF21638C934%7D&file=Pressemitteilung%20Sana_isa.docx&action=default&mobileredirect=true

Deze persbericht kan als blog en als nieuwsbericht op de website.
Nieuwsbericht graag in plaats van 'Mitarbeiter: Service Desk'.

**Comment by RonaldDijkstra** [comment]
@lennartdefacto when can you do this?

**Comment by lennartdefacto** [comment]
later today (afternoon) I have time. @RonaldDijkstra

**Comment by RonaldDijkstra** [comment]
Alright removed my assignment for this
