### ISSUE TITLE
Design of news items

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#1734]
So I was thinking that the news items on the homepage are way too big. I mean it's supposed to be short news about latest trends/events/activities etc. Now it takes up the whole page.

Here some ideas:
1. I think it would be nice if you could see news and products on one screen when you scroll down.
2. Maybe news should just be a tile with a title.
3. The tiles should be smaller. Like CAPP LMS or CAPP Agile tile size.
4. Titles shouldn't be longer than two lines.

What do you guys think?

**Comment by RonaldDijkstra** [comment]
They actually where like that before. 

1. One screen depends on the user's screen, but can make it so it fits more on smaller screens. 
2. No image?
3. OK! 
4. Agreed

**Comment by michellusthof** [comment]
What is visible above the fold (before you have to scroll down) depends largely on your screen size. But even on my 15-inch the first things I see are a large header/hero and only a part of the news items, so these could definitely be made smaller. What we're offering (products) should be made more visible on the homepage. Similarly, I would suggest to include a header image showing CAPP LMS as well. 

I agree with points 3 and 4. I don't think we should remove images completely from news items, but a catchy title and a short description should be sufficient.

**Comment by RonaldDijkstra** [comment]
> What we're offering (products) should be made more visible on the homepage\

The part with our products once was on the place where now the news block is.

**Comment by lennartdefacto** [comment]
1. Would be nice 
2. Could use an Agile like overlay system where types of news (content, product, event, other) get a (50% transparancy) color overlay baked in the image. Just like we now use colored labels here (thanks to Ronald). Would not remove images all together.
3. I agree with the size (length especially) but that's also a content related thing.
4. Definitely agree with this (something I've struggled with in the past)

**Comment by RonaldDijkstra** [comment]
@lennartdefacto the content in these tiles is big

One example:

>  Dianet, het expertisecentrum voor dialyse, is de eerste klant die met de overzichten en inzichten in CAPP LMS de aantoonbare vakbevoegdheid en vakbekwaamheid van haar medewerkers heeft kunnen aantonen. 

Shorter rewritten

>  Dianet is de eerste klant die met behulp van CAPP LMS de vakbevoegdheid en vakbekwaamheid van haar medewerkers heeft aangetoond.

**Comment by RonaldDijkstra** [comment]
These should be merely teasers. They explain too much atm.

**Comment by lennartdefacto** [comment]
Agree with everything you've said.

**Comment by lennartdefacto** [comment]
Mand.

**Comment by RonaldDijkstra** [comment]
Korf.
