### ISSUE TITLE
content changes to health care page DE

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#1741]
Some content changes:

1. Testimonial of Anne Monier has to be replaced with Alke Stade
2. E-Learning link moet naar https://www.defactolearning.de/e-learning-im-gesundheitswesen/
CAPP Learning & Talent Management link moet naar https://www.defactolearning.de/capp-learning-management/
3. Er is nog een spacing issue --> ...Organisation des Kurssystems und der Seminarverwaltung.
4. Er staat twee keer een stuk over 'Seminarverwaltung und Kursverwaltung'. De tweede keer moet het een andere tekst zijn zie https://defactosoftwarebv.sharepoint.com/:w:/r/_layouts/15/Doc.aspx?sourcedoc=%7B372BB058-8D17-4789-A215-C71258F44E0F%7D&file=gesundheitswesen%20seite.docx&action=default&mobileredirect=true
5. bij de logos missen nog Medius en MHH
6. ik zou bij het deel 'Mehr zum Gesundheitswesen' de links groter willen hebben of ook tegels, maar dat kan op een ander moment.

**Comment by RonaldDijkstra** [comment]
> Er is nog een spacing issue --> ...Organisation des Kurssystems und der Seminarverwaltung.

We should use gathercontent again instead of ms word 👍
