### ISSUE TITLE
Add Performance Support

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#1758]
We made a new solutions page that can be added on the website under Lösungen --> Performance Support with the URL https://www.defactolearning.de/performancesupport

Text can be found here: https://defactosoftwarebv.sharepoint.com/:w:/r/_layouts/15/Doc.aspx?sourcedoc=%7B4aac92ef-aa7d-4399-a8f1-1bdef1b29f8a%7D&action=edit&wdPid=69e3ac81&cid=c1cf3d25-c6eb-45c0-abb6-92944183dafb

**Comment by RonaldDijkstra** [comment]
I would use /performance-support

**Comment by isabelamy** [comment]
sounds good

**Comment by RonaldDijkstra** [comment]
Cool!
