### ISSUE TITLE
New customer meeting landing page

### ISSUE THREAD

**Issue by michellusthof** [DefactoSoftware/website#1834]
We need a simple landing page where customers can signup for three possible 'rondetafelbijeenkomsten', the first one taking place early June. I would suggest to use the endpoint **rondetafelgesprek**

- [ ] Add a form:
Fields:
- Date (dropdown) 
- Name (text)
- Function title (text)
- Organisation (text)
- Email address (text)
- Notes (comment; for possible allergies)) 

- [ ] Add completion message thanking for their signup. (content @michellusthof & @aknoeff)

@RonaldDijkstra: would it be possible to have 1 person signup a colleague using the same form?

**Comment by RonaldDijkstra** [comment]
Always only just 1?

**Comment by michellusthof** [comment]
> Always only just 1?

A person. Arnoud expects 1 or 2 persons for each organisation that will be invited.

**Comment by RonaldDijkstra** [comment]
Every organization can take 2 persons max to the event? Earlier we had a dropdown with something like 'we come with _n_ persons' when a person was registering for an event.

**Comment by RonaldDijkstra** [comment]
> Add completion message thanking for their signup. (content @michellusthof & @aknoeff) 

This must be a different one then we have now at /bedankt?

**Comment by michellusthof** [comment]
> Every organization can take 2 persons max to the event? Earlier we had a dropdown with something like 'we come with _n_ persons' when a person was registering for an event.

Arnoud said he wanted each person coming to the event to be registered fully. So, each individual could do it themselves or we allow one of them to register multiple people, including their details.

> > Add completion message thanking for their signup. (content @michellusthof & @aknoeff)
> 
> This must be a different one then we have now at /bedankt?

We could use that one, but it's a bit generic. I would rather say something like 'Bedankt voor je aanmelding. We zien je graag bij de rondetafelbijeenkomst.' Ideally, you could show a different message depending on the signup date, but that might be too much of an effort considering the size (3 locations, 10-15 people each) of the event.
