### ISSUE TITLE
conversion page e-book

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#1879]
Text: 
[title] E-Book: Abenteuer E-Learning
[subtitle] Laden Sie jetzt unser E-Book herunter und erhalten Sie Tipps und Tricks beim Einsatz von E-Learning.

Example form:
<img width="789" alt="Screenshot 2019-05-21 at 11 52 38" src="https://user-images.githubusercontent.com/5277505/58086732-7d241f00-7bbf-11e9-9c2c-9377ea3f58fb.png">

Button: 
E-Book herunterladen

URL: 
/e-book-abenteuer-elearning

If they filled in info and click download, they get the e-book by email. Formkeep goes too k.walheim@defacto.nl and isabela@defacto.nl

**Comment by RonaldDijkstra** [comment]
They get the e-book by email... that's a first
