### ISSUE TITLE
Deploy German website to defactolearning.de

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#189]
We want to use the URL we own for the German website: www.defactolearning.de 
This wil be better indexed than our current URL on the Dutch site

Some issues with this from my point of view are

- we'll need redirects from currect /de pages to new pages (301 server side would be best, client side secondary) 
- what about the language flag icons in the header of the website? Remove?
- German blog needs to work #87 

**Non technical:**
- we'll need to change all URL's in ze German AdWords campaign
- use search console to make the indexation of new URL's lightning fast
- we'll need to change goal tracking in Google Analytics
- where applicable/possible, we'll need to change incoming links

**Comment by RonaldDijkstra** [comment]
No doubt there's more to this. Shoot!

**Comment by sn3p** [comment]
Deploying to a separate domain works (see https://github.com/DefactoSoftware/website/pull/191), including language switching.

Lets do **redirects** and optimizations in a seperate PR.
Same for **German blog**, which will probably be accompanied with an update to Middleman v4.

**Comment by RonaldDijkstra** [comment]
Alright, sounds good.

**Comment by fatboypunk** [comment]
So we're keeping the defacto.nl/de at first to do the redirects later on?

**Comment by sn3p** [comment]
Right now `build/de*` is removed after building the `nl` site. These pages are broken (404 links, broken lang select) so keeping them available is no option. So if we want to keep these urls accessible we do need redirects.

Can we do redirects through DNS config?

Or do something like this?

```rb
require "rack/rewrite"

use Rack::Rewrite do
  r301 %r{/de/(.*)\.html}, "http://www.defactolearning.de/$1"
end
```

Not sure if this is working, but as a last resort:

```rb
redirect "/de/index.html", to: "http://www.defactolearning.de"
redirect "/de/kontakt.html", to: "http://www.defactolearning.de/kontakt"
```

@tarzan your thoughts?
