### ISSUE TITLE
Introduce CAPP Compliance product page

### ISSUE THREAD

**Issue by michellusthof** [DefactoSoftware/website#1946]
- [ ] Introduce CAPP Compliance logo
- [ ] Add H1 (inside hero)
- [ ] Add on-page navigation menu, using CAPP Compliance logo/base color
- [ ] Add testimonials (short generic quotes)
- [ ] Add introduction
- [ ] Make summary/introduction visually more attractive (graphic?)
- [ ] Add main content
- [ ] Add CTA to download productsheet
- [ ] Redirect KPP & KM product pages to new product page
- [ ] Remove old KPP & KM productsheets

**Comment by RonaldDijkstra** [comment]
Do we have German content for this atm?

**Comment by michellusthof** [comment]
Not at this moment. Dutch Productsheet is currently being translated to German.
