### ISSUE TITLE
Change CAPP LMS icons to CAPP logo

### ISSUE THREAD

**Issue by michellusthof** [DefactoSoftware/website#1947]
On places where we currently use the 'hat' logo, we should use the CAPP logo instead. This includes the main navigation and the product overview on the homepage.

**Comment by RonaldDijkstra** [comment]
What about the Talent Management icon on the German website?

![Screenshot 2019-07-10 at 16 20 11](https://user-images.githubusercontent.com/16101007/60976806-aeeb7380-a32e-11e9-8294-f264f204ae71.png)

**Comment by michellusthof** [comment]
If Agile Learning and the future CAPP Compliance both use the six-cornered shape, I would opt for consistency and use the same shape for LMS too.

**Comment by michellusthof** [comment]
We could also use @fritsypeij's new LMS logo?

**Comment by michellusthof** [comment]
Closed by #1970
