### ISSUE TITLE
CAPP icons not in contrast with background

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/website#1966]
@RonaldDijkstra @fritsypeij probably want inverted versions or something?

![Screenshot 2019-07-30 at 12 46 39](https://user-images.githubusercontent.com/935529/62123445-3b52db80-b2c8-11e9-9de0-678451ac1396.png)

related #1947

**Comment by RonaldDijkstra** [comment]
Most definitely. Give me a direction and I will fix @fritsypeij
