### ISSUE TITLE
[CircleCI] html-proofer fails on wrongly encoded ampersand

### ISSUE THREAD

**Issue by michellusthof** [DefactoSoftware/website#2059]
Lately CircleCI fails when running html-proofer on blog articles as shown below:

>  *  15:38021: ERROR: htmlParseEntityRef: expecting ';' (line 15)

See #2057 and [CircleCI](https://circleci.com/gh/DefactoSoftware/website/5247)

I dived into this issue and it appears to be related to a wrongly encoded ampersand (&), as described [here](https://github.com/gjtorikian/html-proofer/issues/537). 

I first tried fixing the error myself by replacing & with &amp; where this wasn't used before and running 'rake test:nl' locally. This does, however, not fix the issue. Because the body contents get minified, the culprit is particularly hard to pinpoint, but it appears to be related to how the summary/preview for blog articles is generated by Nokigiri:

`<div class=post-preview-body> <p> Net als vorig jaar was ik namens Defacto mee met de Nederlandse delegatie naar de Learning 2019 in Orlando. Dit leerevent wordt jaarlijks georganiseerd door Elliott Masie, waarbij zo’n 1.500 tot 2.000 L&D-professionals in drie dagen vele workshops... <a href="/blog/elliot-masie-learning-2019-data-AI-curation/" class=read-more>Lees verder</a> </p> </div>`

Although the introduction for this particular blog article uses &amp; in the blog file itself, the summary generated uses the unencoded ampersand instead. Once I removed the ampersand entirely from the introduction, html-proofer finished successfully, see #2058

**Comment by RonaldDijkstra** [comment]
> Because the body contents get minified, the culprit is particularly hard to pinpoint, but it appears to be related to how the summary/preview for blog articles is generated by Nokigiri:

This is an easy setting in the config, so you could remove minifying for debuggin.

**Comment by RonaldDijkstra** [comment]
Nokogiri was recently updated right? Maybe it has something to do with that.
