### ISSUE TITLE
Netlify settings

### ISSUE THREAD

**Issue by neetso** [DefactoSoftware/website#2087]
Hi, first sorry for potentially abusing Issues. I just wanted to ask how you manage building multiple sites from this repo in Netlify? (I saw a mention of DNS splitting for Netlify in the code.) I'm trying to achieve the same thing (1 middleman rep/site to n websites). Best regards, Matt

**Comment by RonaldDijkstra** [comment]
Thanks for your question. Happy to help. 

With Netlify one can make multiple sites from the same repository. For each we use a specific production build command. See the 'Build for Production' section in our Rakefile: https://github.com/DefactoSoftware/website/blob/master/Rakefile

The command takes the LOCALE as a variable. We use this build commands in Netlify. 

For example, for the 🇳🇱 one: 

![Screenshot 2020-01-21 at 09 59 58](https://user-images.githubusercontent.com/16101007/72789901-d5bb2880-3c34-11ea-9d87-70b45e2658dc.png)

We use Cloudflare for DNS settings and point our domain from there to Netlify.

**Comment by neetso** [comment]
Thanks, that's really helpful. I get how it works now.

**Comment by RonaldDijkstra** [comment]
Cool!
