### ISSUE TITLE
Graphic on compliance page about QP shows incorrect number

### ISSUE THREAD

**Issue by christavlaanderen** [DefactoSoftware/website#2128]
The graphic on the compliance page should be improved: https://www.defacto.nl/capp-compliance/

You can see two red dots, but on the left it says '3 afdelingsvereisten niet behaald'
<img width="446" alt="afbeelding" src="https://user-images.githubusercontent.com/49148222/75546864-d90eb480-5a29-11ea-8290-6e70e73a87dc.png">

This should be '2 van 5 afdelingsvereisten niet behaald'

**Comment by sn3p** [comment]
![capp-compliance-kwaliteitspaspoort](https://user-images.githubusercontent.com/935529/75565289-fc4b5b00-5a4d-11ea-9a0d-5fdac40abcb5.png)
