### ISSUE TITLE
Phone number possibly not visible in older browsers 

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#222]
Here's a screenshot provided by a contact of Rob: 

![image001](https://cloud.githubusercontent.com/assets/16101007/15745245/25f8e470-28d1-11e6-90c5-2dea2872704a.png)

- Obviously IE on an older version of Windows (7?)
- `<a href="tel:+31503144832" class="phone">050 3144832</a>`

Needs more investigation

**Comment by RonaldDijkstra** [comment]
![image002](https://cloud.githubusercontent.com/assets/16101007/15745462/2f745092-28d2-11e6-887c-0e52745ebafe.png)

- this user doesn't even see the phone and fax numbers on the contact page, but these do not have any 'protocol' link on them: 
```
<p>T +31 (0)50 3144832<br>
 F +31 (0)50 3186332</p>
```

**Comment by RonaldDijkstra** [comment]
Can reproduce this on Lizette's laptop with IE11 on W7, but only for the footer phone number. The problem here is the tel href.

**Comment by sn3p** [comment]
@RonaldDijkstra http://stackoverflow.com/questions/32005753/text-disappearing-in-ie-11-on-windows-7

> A bug in Windows 7 is causing text to disappear in IE10 and IE11 when the font-feature-settings css property is used. https://connect.microsoft.com/IE/feedbackdetail/view/831964
