### ISSUE TITLE
Sustainable check if page exists on other TLD

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#239]
We need a more sustainable way of checking if the page has it's equivalent on the other TLD.

**Comment by dkhgh** [comment]
Haven't looked at this in a while, wasn't it the case that **every** `page_name.erb` ~~is~~ should be available in each language, but `page_name.locale.erb` is unique to that language? 

Just a question, cause I was wondering the same when looking at a related PR

**Comment by RonaldDijkstra** [comment]
See PR for details. Closed
