### ISSUE TITLE
xing share-button 

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#274]
Xing share-button op de website
https://www.xing.com/companies/defactosoftware

**Comment by sn3p** [comment]
> **Ronald Dijkstra:**
> @matthijs is een snelle manier om het icomoon iconfont uit te breiden met een xing icon?

Yep!

1. Load [selection.json](https://github.com/DefactoSoftware/website/blob/master/source/fonts/selection.json) in [IcoMoon App](https://icomoon.io/app)
2. Search for "xing"
3. Select the icon you want
4. Click the add button in the search input
