### ISSUE TITLE
With build errors deploying is still possible

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#277]
- ~~Since yesterday building is really really slow (even time outs sometimes)~~
- If build errors deploying is still possible

**Comment by fatboypunk** [comment]
Locally for me the about us page is very slow, might have something to do with that

**Comment by sn3p** [comment]
> Locally for me the about us page is very slow, might have something to do with that

About page has always been slower because team (gr)avatars are being fetched.

**Comment by fatboypunk** [comment]
> About page has always been slower because team (gr)avatars are being fetched.

good to know :)

**Comment by RonaldDijkstra** [comment]
That page won't build, and some blogs won't build as wel.. They time-out. 

```
       error  build/blog/wat-we-hebben-geleerd-van-het-opensourcen-van-ons-hobbyproject/index.html
== Instrument (render.resource): 60025.92434799999ms
```

:(

**Comment by RonaldDijkstra** [comment]
It's still slow but at least I can build now.

**Comment by RonaldDijkstra** [comment]
Build problem is gone for now.
