### ISSUE TITLE
Event tracking with Google Analytics 

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#287]
Event is not a main conversion (goal) but still an important action on the website 

- pop up load
- pop up close

Which ultimately gives more data about the conversion of the pop-up like this 

(Ebook downloads through pop-up / sessions with pop-up shown) * 100% = realistic pop-up conversion rate

Or even

(Ebook downloads through pop-up / users who see the pop-up) * 100% 

- click a button (LS page for example) 

Categories: 
Pop-ups, buttons, maybe more

Started working on this this afternoon.

**Comment by RonaldDijkstra** [comment]
So we could give reasons to update or not show  the pop-up on certain pages (relevancy).

**Comment by RonaldDijkstra** [comment]
Should we track interactions with embedded videos?

https://github.com/lunametrics/youtube-google-analytics
https://github.com/sanderheilbron/vimeo.ga.js

**Comment by fatboypunk** [comment]
> Should we track interactions with embedded videos?

If it doesn't cost you much time, yeah why not?
