### ISSUE TITLE
Pop-up too big for small screens

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#313]
> Dankzij de aanbieding 'ontvang gratis ons e-learning handboek' zie ik 1/4 van uw website niet. Niet erg handig, want de optie om dit weg te klikken valt net buiten bereik.

Investigate & fix

**Comment by fatboypunk** [comment]
Browser/os/devise?

**Comment by RonaldDijkstra** [comment]
Chrome, not OS specific, smaller screens on desktops.
