### ISSUE TITLE
Use a "social proof" section on the Homepage

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#334]
As suggested before 
- clients 
- users
- courses created
- courses passed

Or different stuff. Just not just show logos.

**Comment by dkhgh** [comment]
* Certificates passed

**Comment by RonaldDijkstra** [comment]
Great

**Comment by RonaldDijkstra** [comment]
![found](https://cloud.githubusercontent.com/assets/16101007/19806055/74d6e4d2-9d18-11e6-84cb-2e9361385f04.png)

Something like this. Found this on some website.

**Comment by RonaldDijkstra** [comment]
Github Enterprise

![social-proof-github](https://cloud.githubusercontent.com/assets/16101007/20397082/b38cbb5e-ace8-11e6-9346-61cc445a45f2.png)

**Comment by RonaldDijkstra** [comment]
100% geslaagde koppelingen!!!

**Comment by RonaldDijkstra** [comment]
99.x % uptime?

**Comment by RonaldDijkstra** [comment]
I love it when a plan comes together... 😆

**Comment by lennartdefacto** [comment]
Is goed Hannibal Dijkstra :P

**Comment by RonaldDijkstra** [comment]
Haha
