### ISSUE TITLE
Can we remove the user select from navigation links?

### ISSUE THREAD

**Issue by fatboypunk** [DefactoSoftware/website#350]
<img width="544" alt="screen shot 2016-10-26 at 11 10 08" src="https://cloud.githubusercontent.com/assets/1089927/19720071/e691d008-9b6c-11e6-999a-f15a1154bfa2.png">

**Comment by sn3p** [comment]
How do you get this selection, just by dragging?
Usually it's bad practice to use `user-select: none;` unless there is a good reason, e.g. elements that can be toggled or double clicked.

**Comment by fatboypunk** [comment]
> How do you get this selection, just by dragging?

yes
Good reason: it's ugly, get your point though

**Comment by sn3p** [comment]
It's ugly allright :D but very few visitors will ever see this yet you take away control (copy/paste).

**Comment by fatboypunk** [comment]
I know, but copy past nav items? But also this is why i labeled it to question ^^
