### ISSUE TITLE
Mehr doesn't tell us much

### ISSUE THREAD

**Issue by fatboypunk** [DefactoSoftware/website#351]
<img width="1127" alt="screen shot 2016-10-26 at 11 11 30" src="https://cloud.githubusercontent.com/assets/1089927/19720091/015c7280-9b6d-11e6-89f7-a75f03470436.png">

**Comment by fatboypunk** [comment]
It's on more places through the app, maybe change it to:
<img width="760" alt="screen shot 2016-10-26 at 11 14 37" src="https://cloud.githubusercontent.com/assets/1089927/19720203/7e641d1e-9b6d-11e6-89c7-7a3291e22a17.png">

**Comment by RonaldDijkstra** [comment]
Let's work on that
