### ISSUE TITLE
Colors not corresponding

### ISSUE THREAD

**Issue by fatboypunk** [DefactoSoftware/website#352]
<img width="1205" alt="screen shot 2016-10-26 at 11 16 12" src="https://cloud.githubusercontent.com/assets/1089927/19720248/ac604206-9b6d-11e6-87dc-19fca1d464d8.png">

<img width="1425" alt="screen shot 2016-10-26 at 11 16 56" src="https://cloud.githubusercontent.com/assets/1089927/19720264/bb787da8-9b6d-11e6-8957-752a7a1a340d.png">

**Comment by RonaldDijkstra** [comment]
Thanks for pointing this out.
