### ISSUE TITLE
sitemap.xml is being indexed in Google

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/website#374]
Is this normal?

https://www.google.nl/search?q=defacto+animated+logo&oq=defacto+animated+logo&aqs=chrome..69i57.22399j0j7&sourceid=chrome&ie=UTF-8#q=defacto+%22http:%2F%2Fwww.defacto.nl%2Fblog%2Fanimated-loading-indicator-with-isometric-cubes%2F%22

**Comment by RonaldDijkstra** [comment]
Yes although it should not be placed high on the results page with relatively normal search queries.
