### ISSUE TITLE
Blog space between header and body text

### ISSUE THREAD

**Issue by IwannaDJ** [DefactoSoftware/website#398]
<img width="1216" alt="schermafbeelding 2016-11-29 om 11 18 25" src="https://cloud.githubusercontent.com/assets/23186609/20706369/48f98d42-b627-11e6-8200-7ccf65be5bd9.png">

Can we fix the color or space between header and body of text (looking at our blogs now)? On light screens it looks like there is no grey area on top and a lot of space in between.

**Comment by sn3p** [comment]
I'm not really bothered, but we could make the grey background darker at some point.

Low prio issue imo.

**Comment by RonaldDijkstra** [comment]
I like the white spacing alot.

**Comment by RonaldDijkstra** [comment]
FYI this kind of things are not for only the Dutch website
