### ISSUE TITLE
Refresh testimonials on defacto.nl

### ISSUE THREAD

**Issue by IwannaDJ** [DefactoSoftware/website#415]
Can we put extra quotes on the homepage?

These two underneath 'wat anderen zeggen':

<img width="802" alt="schermafbeelding 2016-12-06 om 09 34 51" src="https://cloud.githubusercontent.com/assets/23186609/20918450/5ed98840-bb97-11e6-977a-4f4160958132.png">

Are they good enough or do they need to say more about our companies working together etc.?

**Comment by RonaldDijkstra** [comment]
I prefer the left one in that case, because it's more :)

**Comment by IwannaDJ** [comment]
Says more about our product as well.

**Comment by RonaldDijkstra** [comment]
It's too much about LS. Please consider another one on the homepage about ziekenhuizen/zorg/KPP.

**Comment by IwannaDJ** [comment]
I thought we were gonna do LS and CAPP? I have a bigger testimonial from Ronald van Rheenen almost ready...
