### ISSUE TITLE
Testimonials on /learningspaces/

### ISSUE THREAD

**Issue by IwannaDJ** [DefactoSoftware/website#416]
Can we make a 'wat anderen over ons zeggen' on this page with the following three quotes?

![schermafbeelding 2016-12-06 om 09 43 50](https://cloud.githubusercontent.com/assets/23186609/20918682/9447678a-bb98-11e6-8b4e-f45d3dfa1972.png)

**Comment by RonaldDijkstra** [comment]
Sure, stay tuned!
