### ISSUE TITLE
Rename 'wat anderen zeggen'

### ISSUE THREAD

**Issue by IwannaDJ** [DefactoSoftware/website#423]
Can we rename this to something that is more concrete? Like 'wat anderen over ons zeggen' or 
for LearningSpaces something like: 'These teams use LearningSpaces to make their learning lives more pleasant, social and productive'. 

And for CAPP maybe something like: 'These institutes use CAPP to help them be qualified'. Last one could be better. 

Just think that 'wat anderen zeggen' is a bit old/ boring, not as concrete and could be better.

**Comment by RonaldDijkstra** [comment]
Sure, please translate to dutch and german.

**Comment by IwannaDJ** [comment]
- Wat anderen over ons zeggen
