### ISSUE TITLE
Header navigation dropdowns

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#428]
Examples: 

![menu-stripe](https://cloud.githubusercontent.com/assets/16101007/21309837/25db6d1c-c5e0-11e6-9ba0-00b02910ca6f.png)

![menu-stripe-de](https://cloud.githubusercontent.com/assets/16101007/21310568/405ef3cc-c5e3-11e6-83d4-b2095d991158.png)

A nav like on the Stripe website. I think it adds value because users can easier go from a page deeper in the website to another page, all at different levels. And it feels a bit more dynamic. 

I need textual input for these product items for both the German as the Dutch website. 

An item consists of: 

- Product Name
- Product Short Description 

Below in the tables is what I have now, based on short descriptions I've found on the website. Please copy the tables and change what you want to be changed. You could use this for markdown tables: http://www.tablesgenerator.com/markdown_tables 

The Short Description needs to be Really Short! Consider the one at CAPP Leren & Ontwikkelen as the *de facto* maximum length per description. And they need to describe the single best USP of the products we have. 

## Dutch: @IwannaDJ 
| Name                     | Description                                                   |
|--------------------------|---------------------------------------------------------------|
| CAPP Leren & Ontwikkelen | Geef medewerkers efficiënte tools voor hun ontwikkelprocessen |
| Kwaliteitspaspoort       | Real-time inzicht in vakbevoegdheid                           |
| LearningSpaces           | Een laagdrempelig sociaal leerplatform                        |
| E-Learning Starterkit    | Maak je eigen e-learning content                              |
| 360° Feedback            | Maak een efficiëntieslag in je HRD                            |

## German: @AnneNH 

| Name                  | Description                                                                      |
|-----------------------|----------------------------------------------------------------------------------|
| Bilden                | Ein starkes Learning Management System (LMS)                                     |
| Entwickeln            | Begleiten Sie die Entwicklung Ihrer Mitarbeiter                                  |
| Qualitätspass         | Erhalten Sie eine Übersicht in die Qualifikationen Ihrer Organisation            |
| LearningSpaces        | Führen Sie Regie über Ihren Lernprozess                                          |
| E-Learning Starterkit | Sichern Sie sich mit dem E-Learning Starterkit einen professionellen Start       |
| 360° Feedback         | 360° Feedback ist ein effizientes Tool für eine transparente Personalentwicklung |

**Comment by IwannaDJ** [comment]
Something like this?

| Name                     | Description                                                   |
|--------------------------|---------------------------------------------------------------|
| CAPP Leren & Ontwikkelen | Geef medewerkers efficiënte tools voor hun ontwikkelprocessen |
| Kwaliteitspaspoort       | Real-time inzicht in bevoegd- en bekwaamheid                           |
| LearningSpaces           | Een laagdrempelig sociaal kennisdelingsplatform                        |
| E-Learning Starterkit    | Creëer je eigen e-learning content                              |
| 360° Feedback            | Maak een efficiëntieslag in je HRD                            |

**Comment by RonaldDijkstra** [comment]
Thanks, good!

**Comment by AnneNH** [comment]
| Name                  	| Description                                                           	|
|-----------------------	|-----------------------------------------------------------------------	|
| Bilden                	| Software für ein effizientes Bildungsmanagement und E-Learning        	|
| Entwickeln            	| Bieten Sie nachhaltige und innovative Talententwicklung               	|
| Qualitätspass         	| Schaffen Sie einen Überblick aller Qualifikationen und Kompetenzen    	|
| LearningSpaces        	| Ihr Tool für spielerischen Wissensaustausch und Informelles Lernen    	|
| E-Learning Starterkit 	| Lernen Sie, eigene E-Learning Module zu erstellen                     	|
| 360° Feedback         	| Die Sichtweisen der anderen kennen, um sich selbst weiterzuentwickeln 	|

**Comment by RonaldDijkstra** [comment]
Danke

**Comment by IwannaDJ** [comment]
Ik heb de Nederlandse ook nog even een update gegeven hierboven!
