### ISSUE TITLE
Make event section

### ISSUE THREAD

**Issue by IwannaDJ** [DefactoSoftware/website#429]
Can we make an event/ workshop section on the landing page?

Header: 

**Bezoek ons hier:**

Text:
13 januari staat team LearningSpaces in Zwolle op hogeschool Windesheim tijdens het SAM evenement (link: http://samevent.nl). 
Can we do link on SAM  evenement?

25 januari staat team LearningSpaces op het Noorder eHealth-symposium (link: https://www.ehealthweek.net/event/noorder-ehealth-symposium/) in het UMCG. 
Can we dot the link on Noorderr eHealth-Symposium

**Comment by RonaldDijkstra** [comment]
![yes-we-can](https://cloud.githubusercontent.com/assets/16101007/21311464/92695f78-c5e7-11e6-9bfb-39bfacac5642.jpg)

Misses Titles

**Comment by RonaldDijkstra** [comment]
Okay, made the events the title, see PR.
