### ISSUE TITLE
Some minor issues on smaller viewports

### ISSUE THREAD

**Issue by dkhgh** [DefactoSoftware/website#43]
![img_2458](https://cloud.githubusercontent.com/assets/4135610/7901854/f4f56b1e-079d-11e5-8bb5-4a0c80653fc7.png)
![img_2457](https://cloud.githubusercontent.com/assets/4135610/7901857/f4f7731e-079d-11e5-8aa8-0a0d35ce54d5.png)
![img_2456](https://cloud.githubusercontent.com/assets/4135610/7901856/f4f64b42-079d-11e5-8d33-390262f0a87d.png)
![img_2455](https://cloud.githubusercontent.com/assets/4135610/7901855/f4f5ecf6-079d-11e5-8998-7bf818869e1a.png)

**Comment by RonaldDijkstra** [comment]
Visited all pages and none seem to have troubles with smaller viewports. I guess these aren't problems anymore.

**Comment by dkhgh** [comment]
@RonaldDijkstra so let's close 👍

**Comment by RonaldDijkstra** [comment]
👍
