### ISSUE TITLE
Update the footer

### ISSUE THREAD

**Issue by fatboypunk** [DefactoSoftware/website#439]
it's ~~~2016~~~ 2017 already!

![Uploading Screen Shot 2017-01-03 at 13.51.30.png…]()

**Comment by RonaldDijkstra** [comment]
Thanks

**Comment by fatboypunk** [comment]
why did you close it?

**Comment by RonaldDijkstra** [comment]
Fixed with build & deploy

`year: Time.now.year`

**Comment by fatboypunk** [comment]
Only local?

**Comment by RonaldDijkstra** [comment]
No, it's online

![developing people seit 1987 defacto](https://cloud.githubusercontent.com/assets/16101007/21609537/532c026a-d1c3-11e6-9727-6cbd14bffd64.png)

**Comment by fatboypunk** [comment]
Code is not
