### ISSUE TITLE
https:// currently not working and not on by default

### ISSUE THREAD

**Issue by jessedijkstra** [DefactoSoftware/website#443]
With the recent uprise in privacy awareness a lot of sites are moving to HTTPS by default. Google is suspected to even [favour sites with SSL enabled](http://thenextweb.com/google/2015/12/17/unsecured-websites-are-about-to-get-hammered-in-googles-search-ranking/).

Currently navigating to https://defacto.nl/ gives the following result:

![screen shot 2017-01-09 at 13 39 25](https://cloud.githubusercontent.com/assets/226130/21766903/5797228c-d671-11e6-97d7-34ba9cc0247b.png)

When you add `www` to the URL https://www.defact.nl/ the we hit an insecure SSL certificate:

![screen shot 2017-01-09 at 13 42 21](https://cloud.githubusercontent.com/assets/226130/21766932/76b43100-d671-11e6-8dce-efbf26f73215.png)

**Comment by fatboypunk** [comment]
https://github.com/DefactoSoftware/website/issues/192

**Comment by tarzan** [comment]
you only get this when @ defactoHQ 'cause of the domaincontroller which is DNS.

**Comment by jessedijkstra** [comment]
Closing because of duplicate
