### ISSUE TITLE
Add a page about Service & Support

### ISSUE THREAD

**Issue by LizetteJS** [DefactoSoftware/website#496]
Graag een link naar het Defacto Portaal op de website plaatsen. Je mag zelf bedenken waar :)
Wanneer je geen idee hebt: Vanuit 'contact' in het rijtje? zie printscreen.

Alvast bedankt!
![contact defacto](https://cloud.githubusercontent.com/assets/23236976/23747648/ba37bc12-04c0-11e7-8f8e-23d9ba786d8e.PNG)

**Comment by LizetteJS** [comment]
defactoportaal.learningspaces.io is trouwens de link..

**Comment by RonaldDijkstra** [comment]
Duitsland auch
