### ISSUE TITLE
Improvements CAPP Agile Learning

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#502]
#503:

- orange menu style vloekt with green on mobile
- features images order 
- QR clickable
- separate 123 from other content
- textual improvements
- improve image up-to-date

#505: 
- scroll effect 

## Todo

- better client logos

**Comment by sn3p** [comment]
The side-by-side images and texts could use some mobile enhancement.
An improvement would be ordering it like this on mobile:

```
[image]
[text]

[image]
[text]
```

... which can be accomplished by using flex [`order`](https://developer.mozilla.org/en/docs/Web/CSS/order).

**Comment by RonaldDijkstra** [comment]
Dope

**Comment by sn3p** [comment]
Marcel suggested a little bit more contrast in the content sections.
Maybe the 3 steps can have a light gray background so it's more separated from the other content.

**Comment by RonaldDijkstra** [comment]
- in op het aanbod wat voor jou interessant is

**Comment by sn3p** [comment]
Let's make the QR clickable as well.

**Comment by RonaldDijkstra** [comment]
Let's close this. If there's anything in the future make a new issue pls.
