### ISSUE TITLE
To do list based on lipperhey

### ISSUE THREAD

**Issue by dkhgh** [DefactoSoftware/website#56]
https://www.lipperhey.com/en/analysis/quick/

* [x] add `robots.txt`
* [x] add `sitemap.xml` (middleman can do this right @sn3p )
* [ ] improve load time
* [x] Meta description and keywords
* [ ] The keyword 'defacto ' is not found in all subheadings.

**Comment by RonaldDijkstra** [comment]
- Jobs.defacto.nl links back to Defacto.nl now
- About load time as mentioned in the first post: 
 - Lipperhey gives a green flag (homepage defacto.nl: 0.24 secs, homepage defactolearning.de: 0.17 secs)
 - Siteliner states: The average page load time for your site is 163ms (159 ms for defactolearning.de). The median for all other sites is 595ms. 
 - Screaming Frog SEO Spider gives an average response time of 0.17 secs for defacto.nl, for defactolearning.de 0.14 secs

So this issue can be closed.
