### ISSUE TITLE
less informal copy for /contact

### ISSUE THREAD

**Issue by dkhgh** [DefactoSoftware/website#60]
> Kom gerust een keertje met ons kennismaken of gewoon bijkletsen, de deur staat altijd open. Lunch met ons mee in het souterain met afsluitend een potje tafelvoetbal, of kom vrijdags gezellig mee borrelen onder het genot van een biertje of een wijntje?

is too informal

**Comment by RonaldDijkstra** [comment]
We're working on new better copy -> @IwannadeJonge, so I'll close this issue for now.

**Comment by fatboypunk** [comment]
it's not on the website right? so this is still relevant

**Comment by RonaldDijkstra** [comment]
True, will be in other issues.

**Comment by IwannaDJ** [comment]
We vinden het fijn om van de bezoekers van onze site te horen. Laat een opmerking of vraag achter in de het formulier hier beneden of in de chat.  

Ons mooie pand ligt op 2 minuten lopen vanaf het Centraal Station in Groningen. Kom je met de auto? Geen probleem, we hebben genoeg parkeerplekken. 

Je kunt op afspraak bij ons langskomen voor een kennismaking of om eens bij te praten, bel daarvoor met Esther op het nummer hieronder.
