### ISSUE TITLE
English CAPP Productsheet?

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#600]
Do we have an English CAPP Productsheet, and if we do, where is it?

**Comment by RonaldDijkstra** [comment]
Only found a real old one. So w need to remove this at first.

**Comment by RonaldDijkstra** [comment]
#669

**Comment by mildaskl** [comment]
Yes, removing it is the only option for now. Maybe we could translate the new one from dutch to English and then add it later. Use the same design etc.
