### ISSUE TITLE
English: which clients in client blocks?

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#619]
We have two different client blocks.
One is used on several places, like the homepage.
The other one is on the CAPP Agile Learning page. 

I'd like to know which clients we want to show on these blocks. For now the same as on the Dutch website are in the blocks.

**Comment by mildaskl** [comment]
Pandadoc, Doppio academy, Shopgate, UMCG, Radboud and lets throw in the biggest German one.
