### ISSUE TITLE
Transfer blogs

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#624]
- [x] http://blog.learningspaces.io/using-your-potential-knowledge-employee-is-what-makes-a-company/
- [x] http://blog.learningspaces.io/wrong-estimation-or-opinion-formation-largest-internet-company-by-2030/
- [x] http://blog.learningspaces.io/ending-the-lms-era-for-organisations/
- [x] http://blog.learningspaces.io/focus-your-teams-ability-to-scale-knowledge/
- [x] http://blog.learningspaces.io/micro-future-2/
- [x] http://blog.learningspaces.io/questions-and-answers/
- [x] http://blog.learningspaces.io/teamwork-is-it-being-redefined/
- [x] http://blog.learningspaces.io/today-and-social-learning-theory/
- [x] http://blog.learningspaces.io/intergenerational-knowledge-transfer/
- [x] http://blog.learningspaces.io/attributes-of-a-leader/
- [x] http://blog.learningspaces.io/learning-in-the-age-of-the-tutorial/
- [x] http://blog.learningspaces.io/lost-and-found-generation-z/
- [x] http://blog.learningspaces.io/give-them-knowledge-and-games/

**Comment by mildaskl** [comment]
Blog links:

http://blog.learningspaces.io/using-your-potential-knowledge-employee-is-what-makes-a-company/

http://blog.learningspaces.io/wrong-estimation-or-opinion-formation-largest-internet-company-by-2030/

http://blog.learningspaces.io/ending-the-lms-era-for-organisations/

http://blog.learningspaces.io/focus-your-teams-ability-to-scale-knowledge/

http://blog.learningspaces.io/micro-future-2/

http://blog.learningspaces.io/questions-and-answers/

http://blog.learningspaces.io/teamwork-is-it-being-redefined/

http://blog.learningspaces.io/today-and-social-learning-theory/

http://blog.learningspaces.io/intergenerational-knowledge-transfer/

http://blog.learningspaces.io/attributes-of-a-leader/

http://blog.learningspaces.io/learning-in-the-age-of-the-tutorial/

http://blog.learningspaces.io/lost-and-found-generation-z/

http://blog.learningspaces.io/give-them-knowledge-and-games/

For now these ones should do. The others should be heavily updated.

**Comment by RonaldDijkstra** [comment]
Ouch, those are a lot... :)

**Comment by fatboypunk** [comment]
It's all in markdown though :)

**Comment by RonaldDijkstra** [comment]
Thank god :)

**Comment by fatboypunk** [comment]
Thank ghost/LS team god has nothing to do with this ;)

**Comment by RonaldDijkstra** [comment]
The technical blogs are really good, like http://blog.learningspaces.io/customizing-the-intercom-launcher/
