### ISSUE TITLE
Where to point QR code link on CAPP Agile Learning page?

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#648]
These link to Shared Spaces.

On the Dutch we link to https://zorgdemo.learningspaces.nl/s/qi4Dge-L_qY5aLzJnciT-A 
On the German we link to https://germany.learningspaces.de/s/ikCgK3FBddGP9uu7HcD2Qg

So where do we point this on the English website?

Both are still LS links and need to be changed in the near future to our new CAPP Agile Learning domain, because shared links have to be made again.

**Comment by mildaskl** [comment]
For now here: https://learningspaces.cappagile.com/s/pFcU-F6g-7ji_MkiQW7pYw
I will update the space with the correct hyperlinks when we will have the domain, it's a 5min work.

**Comment by RonaldDijkstra** [comment]
Thank you.
