### ISSUE TITLE
Vacancies/jobs on the website

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/website#65]
> **Hans:** Ik wil graag een salesvacture op de website hebben. Hoe moet ik dat gaan regelen?

Right now we have [jobs.defacto.nl](http://jobs.defacto.nl) but lets place them on the website?

**Comment by sn3p** [comment]
Maybe we can use the `:blog` extension for this as well:
https://middlemanapp.com/basics/blogging/#multiple-blogs-in-a-single-site

**Comment by RonaldDijkstra** [comment]
We link them. Good for now I guess?

**Comment by fatboypunk** [comment]
As an inquiry, why did this reopen?

**Comment by RonaldDijkstra** [comment]
Because jobs.defacto.nl gets not much attention anymore, both internally and externally. 
I hope this makes things better.
