### ISSUE TITLE
console.log and ie8, 9

### ISSUE THREAD

**Issue by ismay** [DefactoSoftware/website#80]
[Console.log messages can crash ie8 and 9](http://stackoverflow.com/a/5473193), surrounding the call to console.log with [this](https://github.com/h5bp/html5-boilerplate/blob/master/dist/js/plugins.js#L1) is a good fix. Haven't checked if this hasn't already been done, but thought I'd file this issue just to be sure.

**Comment by romkebon** [comment]
I feature detect console.log: https://github.com/DefactoSoftware/website/blob/master/source/javascripts/all.js#L36

That should be sufficient right?

**Comment by ismay** [comment]
Ah yeah ok, should be sufficient. The h5bp method is probably overkill. Cool, nevermind then!

**Comment by dkhgh** [comment]
__fun fact:__ @romkebon wrote [this line](https://github.com/DefactoSoftware/website/blob/master/source/javascripts/all.js#L37) blind.

**Comment by ismay** [comment]
damn, noice
