### ISSUE TITLE
Remove default title and meta description

### ISSUE THREAD

**Issue by romkebon** [DefactoSoftware/website#82]
The default description and title were probably not such a good idea...

> **HTML-verbeteringen**
Laatst bijgewerkt 9 jul. 2015
Als u de volgende problemen verhelpt, kunt u de gebruikerservaring en prestaties van uw site verbeteren.

Metabeschrijving |	Pagina's
---|---
Dubbele beschrijvingen in "meta"-tags |	9

Title-tag | Pagina's
---|---
Dubbele "title"-tags | 7

https://www.google.com/webmasters/tools/html-suggestions?siteUrl=http://www.defacto.nl/

**Comment by RonaldDijkstra** [comment]
Fixed in new PR. Closed.
