### ISSUE TITLE
Blog subdirectories + directory_indexes == fail

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/website#83]
Middleman [blog subdirectories](https://middlemanapp.com/basics/blogging/#article-subdirectory) with assets doesn't go to well with `directory_indexes`.
[Issue](https://github.com/middleman/middleman/issues/818), [issue](https://github.com/middleman/middleman/issues/980) and [blog post](http://cbjohnson.info/blog/2013/12/blog-images-middleman/) describing this problem.

For example building:
```
source/blog/2011-10-18-blog-article.html.markdown
source/blog/2011-10-18-blog-article/photo.jpg
```

Throws and error:
```
== Finishing Request: blog/blog-article/index.html (0.04s)
      create  build/blog/blog-article/index.html
       error  build/blog/blog-article/index.html
File exists - /Users/snap/Git/website/build/blog/blog-article
```

Because `photo.jpg` is build as `build/blog/blog-article`.

#### Workaround

I [solved](https://github.com/DefactoSoftware/website/commit/0ce2c166c4d009b40c8d8cdc04aabfbc9af84232) (workaround) this by storing blog attachments in `images/blog` directory.

#### Possible solution

Disable `directory_indexes` in middleman and use `clean_urls` on [divshot](https://docs.divshot.com/guides/routing).

>  **clean_urls**
If true, Divshot will automatically drop .html extensions from your files. For more information see the [routing guide](https://docs.divshot.com/guides/routing).

**Comment by RobertFischer** [comment]
Just encountered this, too.

**Comment by schoenwaldnils** [comment]
Same problem here. 
Any progress on this issue?

**Comment by sn3p** [comment]
> Same problem here. 
> Any progress on this issue?

@schoenwaldnils sorry for the late reply. I don't think we've ever fixed this.
I think we were using Middleman v3.x back then, so this might be solved in v4.x.

If anyone finds a solution I'm still interested in hearing it :)
