### ISSUE TITLE
Referentie Kristel! 

### ISSUE THREAD

**Issue by jejote** [DefactoSoftware/website#85]
Binnen Máxima Medisch Centrum (MMC) was behoefte aan een systeem waarin de MMC-(zorg)professional gestimuleerd wordt om continu zijn of haar bevoegd- en bekwaamheden bij te houden, zodat de beste zorg met een herkenbaar profiel kan worden geboden. Samen met Defacto is hiervoor het Kwaliteitspaspoort geïmplementeerd.

Vooraf aan de implementatie van het Kwaliteitspaspoort is door verschillende afdelingen, waaronder Afdeling HRM en afdeling Kwaliteit & Veiligheid, hard gewerkt om de basis op orde te krijgen. We hebben gekozen voor een duurzame oplossing waarin realtime de actuele personeelsgegevens en het daaraan gekoppelde profiel beschikbaar is.

Daarnaast vraagt het Kwaliteitspaspoort een cultuur met als uitgangspunt dat de medewerker zelf de regie neemt over de eigen deskundigheid. Van belang is dat managers en afdelingshoofden een cultuur bekrachtigen waarin men elkaar kan aanspreken en ook aanspreekbaar is op het volgen van protocollen zodat men met elkaar zorg van topkwaliteit biedt.

Tijdens de implementatie van het Kwaliteitspaspoort merk je dat Defacto een hechte samenwerkingsrelatie aangaat. Zij willen weten wat er speelt in de organisatie en kunnen daardoor constructief met ons meedenken. Het samenwerken met de mensen van Defacto heeft ons geholpen om de basis op orde te krijgen. Samen met Defacto werken we aan continue verbetering van het Kwaliteitspaspoort, zowel technisch als functioneel.

Zo zijn onze medewerkers nu aantoonbaar bekwaam. Voorbehouden- en risicovolle handelingen worden nu door assessoren op de werkvloer getoetst. Dit is efficiënt en biedt enorm veel inzicht. Met behulp van Defacto beschikken leidinggevenden over (stuur)informatie en zijn onze (zorg)professionals bewust bezig met hun eigen ontwikkeling en nemen zij hierin nu zelf de verantwoordelijkheid.

Kristel Vissers

Projectleider Kwaliteitspaspoort MMC

**Comment by sn3p** [comment]
Added, in German as well.
