### ISSUE TITLE
picture of e-learning book 

### ISSUE THREAD

**Issue by isabelamy** [DefactoSoftware/website#91]
still in dutch on the german website

**Comment by dkhgh** [comment]
do we have an image of the german one?

**Comment by sn3p** [comment]
I couldn't find it, so maybe we need to make it.
I'm game @isabelamy just come and get me and we'll make it :dancer:

**Comment by isabelamy** [comment]
[Abenteuer E-Learning.pdf](https://github.com/DefactoSoftware/website/files/3530/Abenteuer.E-Learning.pdf)
here is the e-learning book @sn3p maybe we can just take a screenshot of it. or do we need an actual picture of the book @dkhgh ?

**Comment by sn3p** [comment]
@isabelamy is there a printed version for the German e-book?

**Comment by dkhgh** [comment]
Yep

**Comment by sn3p** [comment]
![ebook-deutschland](https://cloud.githubusercontent.com/assets/935529/10305067/41fd3812-6c1e-11e5-9d26-6df2f0841a58.png)

**Comment by isabelamy** [comment]
nice!
