### ISSUE TITLE
Fouten in blog BB

### ISSUE THREAD

**Issue by pgvandelden** [DefactoSoftware/website#921]
- _niveau's_ is fout
- _Het meedenken in organisatorische structuren is juist wat de consultants van onschatbare waarde maken_ is fout
- _Bij deze processen adviseert de consultant om deze in goede banen te leiden_ is vreemd
- _De klant heeft behoefte aan en de implementatie van onze software is een weg daarnaartoe._ is vreemd

**Comment by sdegeus** [comment]
Made the text amends - thanks for the feedback!
