### ISSUE TITLE
What to do with the LS blog?

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/website#963]
http://blog.learningspaces.io

Think we moved some posts to the Defacto website, but not all right?

Maybe we can add `rel=canonical` to the blog header and link them to the Defacto website?
We had nice traffic on some posts, so might be worth the trouble.

**Comment by dkhgh** [comment]
There's no real need to close it right? Is this our digital ocean droplet running Ghost?

**Comment by RonaldDijkstra** [comment]
> Think we moved some posts to the Defacto website, but not all right?

yes

**Comment by sn3p** [comment]
> There's no real need to close it right?

Agreed. But some posts have a pretty good page ranking, which would be a shame to go to waste. The LS blog is not discoverable anymore through our website(s).

If we could add `canonical` urls we could link them together and keep the ranking advantage, right?

**Comment by fatboypunk** [comment]
> There's no real need to close it right? Is this our digital ocean droplet running Ghost?

yea it is

**Comment by RonaldDijkstra** [comment]
> If we could add canonical urls we could link them together and keep the ranking advantage, right?

With the canonical tag you say "yo this is the original version of this page", so I think there's no real ranking advantage in canonical tags. To transfer link juice server side redirects would be best.
