### ISSUE TITLE
How about a Developers Blog?

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/website#977]
Talked about it with some devs, and I think it would be nice to have a Developers Blog.
And we already have some nice posts on the LS/defacto blog.

Related #963

**Comment by dkhgh** [comment]
we used to have one, gonna look for it

**Comment by RonaldDijkstra** [comment]
Developers blog is a great idea!

**Comment by RonaldDijkstra** [comment]
I like this: https://github.com/DefactoSoftware/devblog

We can work on that.

**Comment by RonaldDijkstra** [comment]
Do we continue this?

**Comment by sn3p** [comment]
I'm still up for this!

If a dev team takes itself serious it needs a devblog 🏆

**Comment by RonaldDijkstra** [comment]
👍

**Comment by RonaldDijkstra** [comment]
https://h01000110.github.io/windows-95/ this theme? ;-)

**Comment by sn3p** [comment]
Prefer something that looks like Medium or Ghost, for example:

- https://blackrockdigital.github.io/startbootstrap-clean-blog-jekyll/ ([Github](https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll))
- http://rosario.io ([Github](https://github.com/rosario/kasper))
- https://myjekyll.github.io/jasper/ ([Github](https://github.com/myJekyll/jasper))

**Comment by RonaldDijkstra** [comment]
We should just publish dev blogs in the regular blog.
